import './../../globals.css';
import Sidebar from './../../components/layouts/Sidebar';
export const metadata = {
	title: 'SabiVoter || Admin',
	description: 'Generated by create next app',
};

export default function DashboardLayout({ children }) {
	return (
		<>
			<section className="flex flex-col md:flex-row ">
				<Sidebar />
				<main className="w-full bg-white">{children}</main>
			</section>
		</>
	);
}
